"""end

Revision ID: 84002669de77
Revises: e62647f10a93
Create Date: 2023-05-31 14:55:37.116927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84002669de77'
down_revision = 'e62647f10a93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('clid', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('region', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('city', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'locations', 'user', ['clid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'region')
    op.drop_column('locations', 'clid')
    # ### end Alembic commands ###
