"""2

Revision ID: f56d1a000a13
Revises: 84002669de77
Create Date: 2023-05-31 16:08:12.292215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56d1a000a13'
down_revision = '84002669de77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('%%',
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('persentage', sa.Text(), nullable=True)
    )
    op.drop_table('locations')
    op.add_column('info', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('info', sa.Column('region', sa.Text(), nullable=True))
    op.add_column('info', sa.Column('city', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'city')
    op.drop_column('info', 'region')
    op.drop_column('info', 'country')
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clid'], ['user.id'], name='locations_clid_fkey')
    )
    op.drop_table('%%')
    # ### end Alembic commands ###
